baseURL = "https://chris.boyle.name/"
languageCode = "en-gb"
defaultContentLanguage = "en"
title = "Chris Boyle"
theme = "hugo-bootstrap-5"
paginate = 5
paginatePath = "page"

[module.imports]
  path = "github.com/chrisboyle/victor-private"
[module.imports.mounts]
  source = "content"
  target = "content"

[services.rss]
limit = 6

[params]
  date_format = "2 January 2006"

[taxonomies]
  tag = "tags"

[permalinks]
  blog = "/blog/:year/:month/:slug/"

[[menu.main]]
  url = "/"
  name = "Blog"
  weight = 1

[[menu.main]]
  url = "/cv/"
  name = "CV"
  weight = 2

[[menu.main]]
  url = "/projects/"
  name = "Projects"
  weight = 3
